services:
  traefik:
    image: ghcr.io/eugenmayer/traefik:2.x
    environment:
      TRAEFIK_DOCKER_ENABLE: 'true'
      TRAEFIK_ADMIN_ENABLE: 'true'
      TRAEFIK_ADMIN_SSL: 'false'
      TRAEFIK_LOG_LEVEL: 'info'
      TRAEFIK_DOCKER_DEFAULT_RULE: 'Host(`{{ normalize .Name }}.docker.lan`)'
      TRAEFIK_ADMIN_DOMAIN: traefik.local
    ports:
      - 80:8080 # access your lb here, so http://web1.docker-image-traefik.docker.lan
      #- 443:8443 # admin backend under https://localhost/dashboard
    volumes:
      #- certs:/mnt/certs
      #- filestorage:/mnt/filestorage
      #- acme:/mnt/acme
      ## mount our docker socket so our docker container can be discovered
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: false
    networks:
      - tc-net
networks:
  tc-net:
    external: true

#configs:
#  env_config:
#    file: ./.env
